language: c

branches:
  only:
    - master

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - sudo wget http://downloads.arduino.cc/arduino-1.8.6-linux64.tar.xz
  - sudo tar xf arduino-1.8.6-linux64.tar.xz
  - sudo mv arduino-1.8.6 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino

install:
  - sudo wget https://github.com/esp8266/Arduino/archive/master.zip
  - sudo unzip master.zip
  - sudo mv Arduino-master/libraries/ESP8266WiFi /usr/local/share/arduino/libraries
  - sudo wget https://github.com/knolleary/pubsubclient/archive/master.zip
  - sudo unzip master.zip
  - sudo mv pubsubclient-master /usr/local/share/arduino/libraries

script:
  - arduino --verify mqtt-temp-publisher.ino
