language: c

env:
  - BOARD=esp8266:esp8266:nodemcuv2:CpuFrequency=80,FlashSize=4M3M

branches:
  only:
    - master

before_install:
  - sudo wget http://downloads.arduino.cc/arduino-1.8.6-linux64.tar.xz
  - sudo tar xf arduino-1.8.6-linux64.tar.xz
  - sudo mv arduino-1.8.6 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino

install:
  - arduino --pref "boardsmanager.additional.urls=http://arduino.esp8266.com/stable/package_esp8266com_index.json" --save-prefs
  - arduino --install-boards esp8266:esp8266
  - arduino --board $BOARD --save-prefs
  - sudo wget https://github.com/knolleary/pubsubclient/archive/master.zip
  - sudo unzip master.zip
  - sudo mv pubsubclient-master /usr/local/share/arduino/libraries

script:
  - arduino --verify --board $BOARD mqtt-temp-publisher.ino

notifications:
  email:
    on_success: never
    on_failure: never
